export * from './car-brands/car-brands.component';
export * from './modules/modules.component';
export * from './notification/notification.component';
export * from './setting/setting.component';
export * from './tasks/tasks.component';
export * from './page-not-found/page-not-found.component';
export * from './brand-details/brand-details.component';
export * from './menu-item/menu-item.component';
export * from './pages.module';
